#!/bin/bash
# .bash_exports

export PATH=$PATH:/home/lordnaver/.local/bin

# default editor
export EDITOR=vim
export VISUAL=vim

# bash exports
export HISTFILE=~/.bash/history

# config
export XDG_CONFIG_HOME=$HOME/.config

# ssh/gpg settings
export SSH_CONFIG_DIR=$HOME/.CONFIG/SSH
#export VIMINIT='source ~/.vim/vimrc'
export TMUX_CONF=~/.config/tmux/tmux.conf
export GPG_TTY=$(tty)
